language: node_js

node_js:
  - 12

script:
  - commitlint-travis
  - npm test

jobs:
  include:
    - stage: release
      if: branch = master
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
